In [4]:
import pandas as pd

# Load CSV files
df1 = pd.read_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/demuxx/DS2/ds2.meta.csv")
df2 = pd.read_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Cell_ranger_outputs_sepsis/DS2/DS2_18102024/outs/per_sample_outs/DS2_18102024/count/vireo_out/donor_ids.tsv",sep = "\t")
# # Ensure df1 has 'barcode' as a column
# df1 = df1.reset_index().rename(columns={"index": "barcode"})

df1.loc[df1["DoubletStatus"] == "Doublet", "Donor"] = "Doublet"

In [126]:
merged_df = df1.merge(df2[["barcode", "donor_id"]], on="barcode", how="left")

In [129]:
donor_counts = merged_df.groupby(["donor_id", "Donor"]).size().reset_index(name="count")
#print("Donor counts per donor_id:")
print(donor_counts.sort_values(by=["donor_id", "count"], ascending=[True, False]).to_string(index=False))
donor_counts.to_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/donor_id_per_Donor.csv", index=False)

  donor_id    Donor  count
    donor0   B40448    671
    donor0  Doublet    394
    donor0 Negative     29
    donor0   B30803      3
    donor0   B10148      2
    donor0   B10678      2
    donor0   B30864      2
    donor0   B30248      1
    donor1   B10148    743
    donor1  Doublet     51
    donor1 Negative     16
    donor1   B40448      4
    donor1   B10237      2
    donor1   B30248      2
    donor1   B10678      1
    donor1   B30477      1
    donor2   B10237    652
    donor2  Doublet     55
    donor2   B10148      3
    donor2   B10678      3
    donor2   B40448      3
    donor2 Negative      3
    donor2   B30864      1
    donor3   B30248    782
    donor3  Doublet     78
    donor3   B10148      5
    donor3 Negative      2
    donor3   B10237      1
    donor3   B10678      1
    donor3   B30477      1
    donor3   B40448      1
    donor4   B30796    858
    donor4  Doublet     44
    donor4   B10148      5
    donor4 Negative      5
    donor4   B10678      2
    donor4   B30864      2
    donor4   B40448      2
    donor4   B30248      1
    donor4   B30803      1
    donor5   B30803   1038
    donor5  Doublet     59
    donor5 Negative      6
    donor5   B10148      3
    donor5   B10237      2
    donor5   B10678      1
    donor6   B10678    726
    donor6  Doublet     65
    donor6 Negative      4
    donor6   B10148      3
    donor6   B30803      2
    donor6   B30248      1
    donor6   B30796      1
    donor7   B30864    953
    donor7  Doublet     63
    donor7 Negative      3
    donor7   B30248      2
    donor7   B30803      2
    donor7   B10678      1
    donor7   B30477      1
    donor8   B30477   1058
    donor8  Doublet     99
    donor8   B30864      3
    donor8 Negative      3
    donor8   B40448      2
    donor8   B10148      1
    donor8   B10237      1
    donor8   B10678      1
    donor8   B30248      1
   doublet  Doublet    995
   doublet   B10237      7
   doublet   B40448      6
   doublet   B10148      5
   doublet   B30248      4
   doublet Negative      4
   doublet   B30864      3
   doublet   B10678      1
   doublet   B30477      1
   doublet   B30796      1
   doublet   B30803      1
unassigned  Doublet     42
unassigned   B10148     24
unassigned   B40448     19
unassigned   B10678     16
unassigned   B10237     12
unassigned   B30864     11
unassigned   B30803     10
unassigned Negative     10
unassigned   B30248      8
unassigned   B30796      7
unassigned   B30477      4

In [132]:
donor_counts1 = merged_df.groupby(["Donor", "donor_id"]).size().reset_index(name="count")
#print("Donor counts per donor_id:")
print(donor_counts1.sort_values(by=["Donor", "count"], ascending=[True, False]).to_string(index=False))
donor_counts1.to_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/Donor_per_id.csv", index=False)

   Donor   donor_id  count
  B10148     donor1    743
  B10148 unassigned     24
  B10148     donor3      5
  B10148     donor4      5
  B10148    doublet      5
  B10148     donor2      3
  B10148     donor5      3
  B10148     donor6      3
  B10148     donor0      2
  B10148     donor8      1
  B10237     donor2    652
  B10237 unassigned     12
  B10237    doublet      7
  B10237     donor1      2
  B10237     donor5      2
  B10237     donor3      1
  B10237     donor8      1
  B10678     donor6    726
  B10678 unassigned     16
  B10678     donor2      3
  B10678     donor0      2
  B10678     donor4      2
  B10678     donor1      1
  B10678     donor3      1
  B10678     donor5      1
  B10678     donor7      1
  B10678     donor8      1
  B10678    doublet      1
  B30248     donor3    782
  B30248 unassigned      8
  B30248    doublet      4
  B30248     donor1      2
  B30248     donor7      2
  B30248     donor0      1
  B30248     donor4      1
  B30248     donor6      1
  B30248     donor8      1
  B30477     donor8   1058
  B30477 unassigned      4
  B30477     donor1      1
  B30477     donor3      1
  B30477     donor7      1
  B30477    doublet      1
  B30796     donor4    858
  B30796 unassigned      7
  B30796     donor6      1
  B30796    doublet      1
  B30803     donor5   1038
  B30803 unassigned     10
  B30803     donor0      3
  B30803     donor6      2
  B30803     donor7      2
  B30803     donor4      1
  B30803    doublet      1
  B30864     donor7    953
  B30864 unassigned     11
  B30864     donor8      3
  B30864    doublet      3
  B30864     donor0      2
  B30864     donor4      2
  B30864     donor2      1
  B40448     donor0    671
  B40448 unassigned     19
  B40448    doublet      6
  B40448     donor1      4
  B40448     donor2      3
  B40448     donor4      2
  B40448     donor8      2
  B40448     donor3      1
 Doublet    doublet    995
 Doublet     donor0    394
 Doublet     donor8     99
 Doublet     donor3     78
 Doublet     donor6     65
 Doublet     donor7     63
 Doublet     donor5     59
 Doublet     donor2     55
 Doublet     donor1     51
 Doublet     donor4     44
 Doublet unassigned     42
Negative     donor0     29
Negative     donor1     16
Negative unassigned     10
Negative     donor5      6
Negative     donor4      5
Negative     donor6      4
Negative    doublet      4
Negative     donor2      3
Negative     donor7      3
Negative     donor8      3
Negative     donor3      2

In [133]:
# 2. Compute total per donor_id
total_counts_donor_id = merged_df["donor_id"].value_counts().reset_index()
total_counts_donor_id.columns = ["donor_id", "Total"]
print("\nTotal counts for each donor_id:")
print(total_counts_donor_id.sort_values(by="donor_id").to_string(index=False))

# 3. Compute total per Donor
total_counts_donor = merged_df["Donor"].value_counts().reset_index()
total_counts_donor.columns = ["Donor", "Total"]
print("\nTotal counts for each Donor:")
print(total_counts_donor.sort_values(by="Donor").to_string(index=False))

Total counts for each donor_id:
  donor_id  Total
    donor0   1104
    donor1    820
    donor2    720
    donor3    871
    donor4    920
    donor5   1109
    donor6    802
    donor7   1025
    donor8   1169
   doublet   1028
unassigned    163

Total counts for each Donor:
   Donor  Total
  B10148    794
  B10237    677
  B10678    755
  B30248    802
  B30477   1066
  B30796    867
  B30803   1057
  B30864    975
  B40448    708
 Doublet   1945
Negative     85

In [151]:
f1 = pd.read_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/HTO/qc_meta.csv")
f2 = pd.read_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/SNP/qc_meta.csv")
# # Ensure df1 has 'barcode' as a column
# df1 = df1.reset_index().rename(columns={"index": "barcode"})

f1.loc[f1["DoubletStatus"] == "Doublet", "Donor"] = "Doublet"

mergedf = f1.merge(f2[["barcode", "donor_id"]], on="barcode", how="left")

In [153]:
total_counts_donor_id = mergedf["donor_id"].value_counts().reset_index()
total_counts_donor_id.columns = ["donor_id", "Total"]
print("\nTotal counts for each donor_id:")
print(total_counts_donor_id.sort_values(by="donor_id").to_string(index=False))

# 3. Compute total per Donor
total_counts_donor = mergedf["Donor"].value_counts().reset_index()
total_counts_donor.columns = ["Donor", "Total"]
print("\nTotal counts for each Donor:")
print(total_counts_donor.sort_values(by="Donor").to_string(index=False))

donor_counts_qc = mergedf.groupby(["donor_id", "Donor"]).size().reset_index(name="count")
print(donor_counts_qc.sort_values(by=["donor_id", "count"], ascending=[True, False]).to_string(index=False))

Total counts for each donor_id:
  donor_id  Total
    donor0    700
    donor1    740
    donor2    652
    donor3    786
    donor4    872
    donor5   1037
    donor6    717
    donor7    955
    donor8   1064
unassigned     90

Total counts for each Donor:
   Donor  Total
  B10148    753
  B10237    663
  B10678    718
  B30248    794
  B30477   1061
  B30796    865
  B30803   1038
  B30864    967
  B40448    699
Negative     84
  donor_id    Donor  count
    donor0   B40448    668
    donor0 Negative     28
    donor0   B30803      3
    donor0   B30864      1
    donor1   B10148    719
    donor1 Negative     16
    donor1   B40448      2
    donor1   B10237      1
    donor1   B10678      1
    donor1   B30248      1
    donor2   B10237    642
    donor2   B10148      3
    donor2 Negative      3
    donor2   B40448      2
    donor2   B10678      1
    donor2   B30864      1
    donor3   B30248    778
    donor3   B10148      4
    donor3 Negative      2
    donor3   B10237      1
    donor3   B30477      1
    donor4   B30796    857
    donor4   B10148      5
    donor4 Negative      5
    donor4   B30864      2
    donor4   B40448      2
    donor4   B30803      1
    donor5   B30803   1028
    donor5 Negative      6
    donor5   B10237      2
    donor5   B10148      1
    donor6   B10678    707
    donor6 Negative      4
    donor6   B10148      2
    donor6   B30803      2
    donor6   B30248      1
    donor6   B30796      1
    donor7   B30864    949
    donor7 Negative      3
    donor7   B30248      2
    donor7   B30477      1
    donor8   B30477   1055
    donor8 Negative      3
    donor8   B30864      2
    donor8   B10148      1
    donor8   B10237      1
    donor8   B30248      1
    donor8   B40448      1
unassigned   B40448     18
unassigned   B10148     15
unassigned   B10237     10
unassigned Negative     10
unassigned   B10678      9
unassigned   B30864      9
unassigned   B30248      7
unassigned   B30796      6
unassigned   B30477      3
unassigned   B30803      3

In [144]:
merged = pd.read_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/both/qc_meta.csv")
merged.loc[merged["DoubletStatus"] == "Doublet", "Donor"] = "Doublet"
donor_counts_qc = merged.groupby(["donor_id", "Donor"]).size().reset_index(name="count")
print(donor_counts_qc.sort_values(by=["donor_id", "count"], ascending=[True, False]).to_string(index=False))

  donor_id    Donor  count
    donor0   B40448    668
    donor0  Doublet    391
    donor0 Negative     28
    donor0   B30803      3
    donor0   B30864      1
    donor1   B10148    719
    donor1  Doublet     50
    donor1 Negative     16
    donor1   B40448      2
    donor1   B10237      1
    donor1   B10678      1
    donor1   B30248      1
    donor2   B10237    642
    donor2  Doublet     54
    donor2   B10148      3
    donor2 Negative      3
    donor2   B40448      2
    donor2   B10678      1
    donor2   B30864      1
    donor3   B30248    778
    donor3  Doublet     77
    donor3   B10148      4
    donor3 Negative      2
    donor3   B10237      1
    donor3   B30477      1
    donor4   B30796    857
    donor4  Doublet     43
    donor4   B10148      5
    donor4 Negative      5
    donor4   B30864      2
    donor4   B40448      2
    donor4   B30803      1
    donor5   B30803   1028
    donor5  Doublet     58
    donor5 Negative      6
    donor5   B10237      2
    donor5   B10148      1
    donor6   B10678    707
    donor6  Doublet     63
    donor6 Negative      4
    donor6   B10148      2
    donor6   B30803      2
    donor6   B30248      1
    donor6   B30796      1
    donor7   B30864    949
    donor7  Doublet     63
    donor7 Negative      3
    donor7   B30248      2
    donor7   B30477      1
    donor8   B30477   1055
    donor8  Doublet     99
    donor8 Negative      3
    donor8   B30864      2
    donor8   B10148      1
    donor8   B10237      1
    donor8   B30248      1
    donor8   B40448      1
   doublet   B10237      6
   doublet   B40448      6
   doublet   B30248      4
   doublet Negative      4
   doublet   B10148      3
   doublet   B30864      3
   doublet   B30477      1
   doublet   B30796      1
   doublet   B30803      1
unassigned  Doublet     40
unassigned   B40448     18
unassigned   B10148     15
unassigned   B10237     10
unassigned Negative     10
unassigned   B10678      9
unassigned   B30864      9
unassigned   B30248      7
unassigned   B30796      6
unassigned   B30477      3
unassigned   B30803      3

In [142]:
Donor_counts_qc = merged.groupby(["Donor","donor_id"]).size().reset_index(name="count")
print(Donor_counts_qc.sort_values(by=["Donor", "count"], ascending=[True, False]).to_string(index=False))

   Donor   donor_id  count
  B10148     donor1    719
  B10148 unassigned     15
  B10148     donor4      5
  B10148     donor3      4
  B10148     donor2      3
  B10148    doublet      3
  B10148     donor6      2
  B10148     donor5      1
  B10148     donor8      1
  B10237     donor2    642
  B10237 unassigned     10
  B10237    doublet      6
  B10237     donor5      2
  B10237     donor1      1
  B10237     donor3      1
  B10237     donor8      1
  B10678     donor6    707
  B10678 unassigned      9
  B10678     donor1      1
  B10678     donor2      1
  B30248     donor3    778
  B30248 unassigned      7
  B30248    doublet      4
  B30248     donor7      2
  B30248     donor1      1
  B30248     donor6      1
  B30248     donor8      1
  B30477     donor8   1055
  B30477 unassigned      3
  B30477     donor3      1
  B30477     donor7      1
  B30477    doublet      1
  B30796     donor4    857
  B30796 unassigned      6
  B30796     donor6      1
  B30796    doublet      1
  B30803     donor5   1028
  B30803     donor0      3
  B30803 unassigned      3
  B30803     donor6      2
  B30803     donor4      1
  B30803    doublet      1
  B30864     donor7    949
  B30864 unassigned      9
  B30864    doublet      3
  B30864     donor4      2
  B30864     donor8      2
  B30864     donor0      1
  B30864     donor2      1
  B40448     donor0    668
  B40448 unassigned     18
  B40448    doublet      6
  B40448     donor1      2
  B40448     donor2      2
  B40448     donor4      2
  B40448     donor8      1
 Doublet     donor0    391
 Doublet     donor8     99
 Doublet     donor3     77
 Doublet     donor6     63
 Doublet     donor7     63
 Doublet     donor5     58
 Doublet     donor2     54
 Doublet     donor1     50
 Doublet     donor4     43
 Doublet unassigned     40
Negative     donor0     28
Negative     donor1     16
Negative unassigned     10
Negative     donor5      6
Negative     donor4      5
Negative     donor6      4
Negative    doublet      4
Negative     donor2      3
Negative     donor7      3
Negative     donor8      3
Negative     donor3      2

In [143]:
# 2. Compute total per donor_id
total_counts_donor_id = merged["donor_id"].value_counts().reset_index()
total_counts_donor_id.columns = ["donor_id", "Total"]
print("\nTotal counts for each donor_id:")
print(total_counts_donor_id.sort_values(by="donor_id").to_string(index=False))

# 3. Compute total per Donor
total_counts_donor = merged["Donor"].value_counts().reset_index()
total_counts_donor.columns = ["Donor", "Total"]
print("\nTotal counts for each Donor:")
print(total_counts_donor.sort_values(by="Donor").to_string(index=False))

Total counts for each donor_id:
  donor_id  Total
    donor0   1091
    donor1    790
    donor2    706
    donor3    863
    donor4    915
    donor5   1095
    donor6    780
    donor7   1018
    donor8   1163
   doublet     29
unassigned    130

Total counts for each Donor:
   Donor  Total
  B10148    753
  B10237    663
  B10678    718
  B30248    794
  B30477   1061
  B30796    865
  B30803   1038
  B30864    967
  B40448    699
 Doublet    938
Negative     84

In [8]:
df1 = pd.read_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/both/qc_meta.csv")
df1= df1[["barcode","Donor","donor_id","DoubletStatus","prob_max","prob_doublet"]]
df2 = pd.read_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/both/qc_SNP_HTO.csv")
df = pd.merge(df1, df2, on="barcode")

In [9]:
df

,barcode,Donor,donor_id,DoubletStatus,prob_max,prob_doublet,B30803,B10148,B40448,B20340,B30477,B10678,B30864,B30248,B30796,B10237
0,AAACCTGAGCGATGAC-1,B30796,donor4,Singlet,1.0,2.830000e-21,0.303170,0.000000,0.000000,0.0,0.514517,0.000000,0.000000,0.487489,4.338322,0.232343
1,AAACCTGAGTACGCCC-1,B30864,donor7,Singlet,1.0,3.610000e-21,0.000000,0.834991,0.198825,0.0,0.155471,2.281850,4.380553,0.273161,0.000000,0.000000
2,AAACCTGAGTACGTTC-1,B30864,donor7,Singlet,1.0,2.740000e-28,0.000000,0.282317,0.000000,0.0,0.514517,0.198744,4.855752,0.000000,0.265076,1.210144
3,AAACCTGAGTGGTAGC-1,B30864,donor7,Singlet,1.0,1.150000e-10,0.000000,0.282317,0.364600,0.0,0.289991,0.000000,5.227569,0.000000,0.265076,0.000000
4,AAACCTGCAGGAATCG-1,B30477,donor8,Singlet,1.0,3.580000e-35,0.000000,0.000000,0.000000,0.0,5.068570,0.364462,0.000000,0.273161,0.000000,0.232343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8575,TTTGTCAGTGATGTCT-1,B10237,donor2,Singlet,1.0,1.120000e-15,0.303170,0.282317,0.198825,0.0,0.155471,0.506582,0.000000,0.000000,0.265076,5.143244
8576,TTTGTCAGTGGAAAGA-1,B30803,donor5,Singlet,1.0,7.970000e-19,3.804748,0.502227,0.364600,0.0,0.155471,0.364462,0.644007,0.663891,0.000000,0.715988
8577,TTTGTCAGTTAGTGGG-1,B30248,donor3,Singlet,1.0,2.620000e-11,0.303170,0.282317,0.198825,0.0,0.155471,0.630994,0.203776,4.013519,0.474406,0.420750
8578,TTTGTCAGTTGCCTCT-1,B30477,donor8,Singlet,1.0,2.050000e-43,0.000000,0.000000,0.364600,0.0,5.040669,0.931805,0.203776,0.273161,0.265076,0.232343
8579,TTTGTCATCAGTTTGG-1,B30864,donor7,Singlet,1.0,3.640000e-26,0.000000,0.282317,0.364600,0.0,0.289991,0.000000,4.867992,0.273161,0.265076,0.000000

In [10]:
# df["donor_id"] = df["donor_id"].astype(str).str.strip()
# df["Donor"] = df["Donor"].astype(str).str.strip()

# # # Remove rows where both donor_id and Donor are exactly "Doublet"
# # df = df[~((df["donor_id"] == "doublet") & (df["Donor"] == "Doublet"))]
df.loc[df["DoubletStatus"] == "Doublet", "Donor"] = "Doublet"
df.loc[df["donor_id"] == "doublet", "donor_id"] = "Doublet"

In [11]:
donor_counts = df.groupby(["donor_id", "Donor"]).size().reset_index(name="count")

# Find the Donor with the max count for each donor_id
max_donor = donor_counts.loc[donor_counts.groupby('donor_id')['count'].idxmax()]

# Create a mapping of donor_id to the Donor with the highest count
donor_id_to_max_donor = max_donor.set_index('donor_id')['Donor'].to_dict()

# Create a mapping of donor_id to the max count
donor_id_to_max_count = max_donor.set_index('donor_id')['count'].to_dict()

# Function to assign the final donor based on maximum count match
def assign_final_donor(row):
    donor_id = row["donor_id"]
    
    # Keep "Doublet" and "Unassigned" as-is
    if donor_id in ["Doublet", "Unassigned"]:
        return donor_id

    max_donor_for_id = donor_id_to_max_donor.get(donor_id)
    max_count_for_id = donor_id_to_max_count.get(donor_id)

    current_donor_count = donor_counts[
        (donor_counts["donor_id"] == donor_id) & 
        (donor_counts["Donor"] == row["Donor"])
    ]["count"].values

    if current_donor_count.size > 0 and current_donor_count[0] == max_count_for_id:
        return max_donor_for_id
    else:
        return donor_id


# Apply the function to assign the final donor
df["SNP_donor"] = df.apply(assign_final_donor, axis=1)

In [12]:
for k, v in donor_id_to_max_donor.items():
    print(f"donor_id '{k}' is most likely Donor '{v}'")

donor_id 'Doublet' is most likely Donor 'B10237'
donor_id 'donor0' is most likely Donor 'B40448'
donor_id 'donor1' is most likely Donor 'B10148'
donor_id 'donor2' is most likely Donor 'B10237'
donor_id 'donor3' is most likely Donor 'B30248'
donor_id 'donor4' is most likely Donor 'B30796'
donor_id 'donor5' is most likely Donor 'B30803'
donor_id 'donor6' is most likely Donor 'B10678'
donor_id 'donor7' is most likely Donor 'B30864'
donor_id 'donor8' is most likely Donor 'B30477'
donor_id 'unassigned' is most likely Donor 'Doublet'

In [13]:
df

,barcode,Donor,donor_id,DoubletStatus,prob_max,prob_doublet,B30803,B10148,B40448,B20340,B30477,B10678,B30864,B30248,B30796,B10237,SNP_donor
0,AAACCTGAGCGATGAC-1,B30796,donor4,Singlet,1.0,2.830000e-21,0.303170,0.000000,0.000000,0.0,0.514517,0.000000,0.000000,0.487489,4.338322,0.232343,B30796
1,AAACCTGAGTACGCCC-1,B30864,donor7,Singlet,1.0,3.610000e-21,0.000000,0.834991,0.198825,0.0,0.155471,2.281850,4.380553,0.273161,0.000000,0.000000,B30864
2,AAACCTGAGTACGTTC-1,B30864,donor7,Singlet,1.0,2.740000e-28,0.000000,0.282317,0.000000,0.0,0.514517,0.198744,4.855752,0.000000,0.265076,1.210144,B30864
3,AAACCTGAGTGGTAGC-1,B30864,donor7,Singlet,1.0,1.150000e-10,0.000000,0.282317,0.364600,0.0,0.289991,0.000000,5.227569,0.000000,0.265076,0.000000,B30864
4,AAACCTGCAGGAATCG-1,B30477,donor8,Singlet,1.0,3.580000e-35,0.000000,0.000000,0.000000,0.0,5.068570,0.364462,0.000000,0.273161,0.000000,0.232343,B30477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8575,TTTGTCAGTGATGTCT-1,B10237,donor2,Singlet,1.0,1.120000e-15,0.303170,0.282317,0.198825,0.0,0.155471,0.506582,0.000000,0.000000,0.265076,5.143244,B10237
8576,TTTGTCAGTGGAAAGA-1,B30803,donor5,Singlet,1.0,7.970000e-19,3.804748,0.502227,0.364600,0.0,0.155471,0.364462,0.644007,0.663891,0.000000,0.715988,B30803
8577,TTTGTCAGTTAGTGGG-1,B30248,donor3,Singlet,1.0,2.620000e-11,0.303170,0.282317,0.198825,0.0,0.155471,0.630994,0.203776,4.013519,0.474406,0.420750,B30248
8578,TTTGTCAGTTGCCTCT-1,B30477,donor8,Singlet,1.0,2.050000e-43,0.000000,0.000000,0.364600,0.0,5.040669,0.931805,0.203776,0.273161,0.265076,0.232343,B30477
8579,TTTGTCATCAGTTTGG-1,B30864,donor7,Singlet,1.0,3.640000e-26,0.000000,0.282317,0.364600,0.0,0.289991,0.000000,4.867992,0.273161,0.265076,0.000000,B30864

In [14]:
#df.to_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/both/ds2.donor.csv", index=False)

In [15]:
hto_columns = ["B30803", "B10148", "B40448", "B20340", "B30477", "B10678", "B30864", "B30248", "B30796", "B10237"]

# Ensure all HTO columns are numeric
df[hto_columns] = df[hto_columns].apply(pd.to_numeric, errors='coerce')

df["best_hto"] = df[hto_columns].idxmax(axis=1)
df

,barcode,Donor,donor_id,DoubletStatus,prob_max,prob_doublet,B30803,B10148,B40448,B20340,B30477,B10678,B30864,B30248,B30796,B10237,SNP_donor,best_hto
0,AAACCTGAGCGATGAC-1,B30796,donor4,Singlet,1.0,2.830000e-21,0.303170,0.000000,0.000000,0.0,0.514517,0.000000,0.000000,0.487489,4.338322,0.232343,B30796,B30796
1,AAACCTGAGTACGCCC-1,B30864,donor7,Singlet,1.0,3.610000e-21,0.000000,0.834991,0.198825,0.0,0.155471,2.281850,4.380553,0.273161,0.000000,0.000000,B30864,B30864
2,AAACCTGAGTACGTTC-1,B30864,donor7,Singlet,1.0,2.740000e-28,0.000000,0.282317,0.000000,0.0,0.514517,0.198744,4.855752,0.000000,0.265076,1.210144,B30864,B30864
3,AAACCTGAGTGGTAGC-1,B30864,donor7,Singlet,1.0,1.150000e-10,0.000000,0.282317,0.364600,0.0,0.289991,0.000000,5.227569,0.000000,0.265076,0.000000,B30864,B30864
4,AAACCTGCAGGAATCG-1,B30477,donor8,Singlet,1.0,3.580000e-35,0.000000,0.000000,0.000000,0.0,5.068570,0.364462,0.000000,0.273161,0.000000,0.232343,B30477,B30477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8575,TTTGTCAGTGATGTCT-1,B10237,donor2,Singlet,1.0,1.120000e-15,0.303170,0.282317,0.198825,0.0,0.155471,0.506582,0.000000,0.000000,0.265076,5.143244,B10237,B10237
8576,TTTGTCAGTGGAAAGA-1,B30803,donor5,Singlet,1.0,7.970000e-19,3.804748,0.502227,0.364600,0.0,0.155471,0.364462,0.644007,0.663891,0.000000,0.715988,B30803,B30803
8577,TTTGTCAGTTAGTGGG-1,B30248,donor3,Singlet,1.0,2.620000e-11,0.303170,0.282317,0.198825,0.0,0.155471,0.630994,0.203776,4.013519,0.474406,0.420750,B30248,B30248
8578,TTTGTCAGTTGCCTCT-1,B30477,donor8,Singlet,1.0,2.050000e-43,0.000000,0.000000,0.364600,0.0,5.040669,0.931805,0.203776,0.273161,0.265076,0.232343,B30477,B30477
8579,TTTGTCATCAGTTTGG-1,B30864,donor7,Singlet,1.0,3.640000e-26,0.000000,0.282317,0.364600,0.0,0.289991,0.000000,4.867992,0.273161,0.265076,0.000000,B30864,B30864

In [16]:
def assign_final_donor(row):
    # Keep Doublet and Unassigned unchanged
    if row["SNP_donor"] in ["Doublet", "Unassigned"]:
        return row["SNP_donor"]
    
    # If prob_max is high and all labels agree, assign the confident Donor
    if row["prob_max"] >= 0.9 and row["Donor"] == row["best_hto"] == row["SNP_donor"]:
        return row["Donor"]
    
    # Otherwise fallback to SNP_donor
    return row["SNP_donor"]

df["fin_donor"] = df.apply(assign_final_donor, axis=1)

In [17]:
df.to_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/both/step1.csv", index=False)
df

,barcode,Donor,donor_id,DoubletStatus,prob_max,prob_doublet,B30803,B10148,B40448,B20340,B30477,B10678,B30864,B30248,B30796,B10237,SNP_donor,best_hto,fin_donor
0,AAACCTGAGCGATGAC-1,B30796,donor4,Singlet,1.0,2.830000e-21,0.303170,0.000000,0.000000,0.0,0.514517,0.000000,0.000000,0.487489,4.338322,0.232343,B30796,B30796,B30796
1,AAACCTGAGTACGCCC-1,B30864,donor7,Singlet,1.0,3.610000e-21,0.000000,0.834991,0.198825,0.0,0.155471,2.281850,4.380553,0.273161,0.000000,0.000000,B30864,B30864,B30864
2,AAACCTGAGTACGTTC-1,B30864,donor7,Singlet,1.0,2.740000e-28,0.000000,0.282317,0.000000,0.0,0.514517,0.198744,4.855752,0.000000,0.265076,1.210144,B30864,B30864,B30864
3,AAACCTGAGTGGTAGC-1,B30864,donor7,Singlet,1.0,1.150000e-10,0.000000,0.282317,0.364600,0.0,0.289991,0.000000,5.227569,0.000000,0.265076,0.000000,B30864,B30864,B30864
4,AAACCTGCAGGAATCG-1,B30477,donor8,Singlet,1.0,3.580000e-35,0.000000,0.000000,0.000000,0.0,5.068570,0.364462,0.000000,0.273161,0.000000,0.232343,B30477,B30477,B30477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8575,TTTGTCAGTGATGTCT-1,B10237,donor2,Singlet,1.0,1.120000e-15,0.303170,0.282317,0.198825,0.0,0.155471,0.506582,0.000000,0.000000,0.265076,5.143244,B10237,B10237,B10237
8576,TTTGTCAGTGGAAAGA-1,B30803,donor5,Singlet,1.0,7.970000e-19,3.804748,0.502227,0.364600,0.0,0.155471,0.364462,0.644007,0.663891,0.000000,0.715988,B30803,B30803,B30803
8577,TTTGTCAGTTAGTGGG-1,B30248,donor3,Singlet,1.0,2.620000e-11,0.303170,0.282317,0.198825,0.0,0.155471,0.630994,0.203776,4.013519,0.474406,0.420750,B30248,B30248,B30248
8578,TTTGTCAGTTGCCTCT-1,B30477,donor8,Singlet,1.0,2.050000e-43,0.000000,0.000000,0.364600,0.0,5.040669,0.931805,0.203776,0.273161,0.265076,0.232343,B30477,B30477,B30477
8579,TTTGTCATCAGTTTGG-1,B30864,donor7,Singlet,1.0,3.640000e-26,0.000000,0.282317,0.364600,0.0,0.289991,0.000000,4.867992,0.273161,0.265076,0.000000,B30864,B30864,B30864

In [18]:
 filtered_df = df[df["fin_donor"].isin(df["donor_id"].unique())].copy()
 filtered_df

,barcode,Donor,donor_id,DoubletStatus,prob_max,prob_doublet,B30803,B10148,B40448,B20340,B30477,B10678,B30864,B30248,B30796,B10237,SNP_donor,best_hto,fin_donor
7,AAACCTGGTGACCAAG-1,Doublet,donor0,Doublet,1.000,4.700000e-04,0.000000,0.967361,4.424706,1.033237,0.408542,0.000000,0.000000,0.000000,0.474406,0.232343,donor0,B40448,donor0
13,AAACCTGTCTCCAACC-1,Doublet,donor0,Doublet,1.000,2.930000e-23,0.000000,0.282317,4.895158,1.033237,0.000000,0.364462,0.000000,0.273161,0.000000,0.232343,donor0,B40448,donor0
15,AAACGGGAGATAGCAT-1,Doublet,donor0,Doublet,1.000,3.710000e-20,0.000000,0.502227,3.473070,1.033237,0.155471,0.198744,0.372974,0.273161,0.000000,0.232343,donor0,B40448,donor0
17,AAACGGGAGATGCCTT-1,Doublet,donor0,Doublet,1.000,4.280000e-20,0.000000,0.502227,4.932316,1.530458,0.289991,0.000000,0.203776,0.487489,0.000000,0.000000,donor0,B40448,donor0
20,AAACGGGAGGGAGTAA-1,Doublet,donor3,Doublet,1.000,2.430000e-06,0.303170,0.682387,0.000000,0.000000,0.155471,0.506582,0.517645,5.757898,0.923326,5.388491,donor3,B30248,donor3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8549,TTTGGTTCACATCCGG-1,Doublet,donor0,Doublet,1.000,4.700000e-25,0.000000,0.682387,3.877292,1.033237,0.408542,0.364462,0.644007,0.663891,0.265076,0.232343,donor0,B40448,donor0
8558,TTTGGTTTCAACGAAA-1,Negative,donor1,Negative,0.976,1.150000e-02,0.303170,1.449735,0.364600,0.000000,0.289991,0.000000,0.203776,0.273161,0.000000,0.000000,donor1,B10148,donor1
8559,TTTGGTTTCACAAACC-1,B10148,donor2,Singlet,0.985,8.710000e-03,0.303170,4.827957,1.163053,0.000000,0.000000,0.630994,0.857025,0.000000,0.474406,0.232343,donor2,B10148,donor2
8563,TTTGTCAAGGGCTCTC-1,Doublet,donor0,Doublet,1.000,2.250000e-06,0.000000,0.834991,5.846181,2.307646,0.155471,0.364462,5.928916,0.813791,6.018761,0.715988,donor0,B30796,donor0
8565,TTTGTCACAAATCCGT-1,Doublet,donor6,Doublet,1.000,9.420000e-37,0.535492,0.502227,0.631205,0.000000,0.408542,5.175560,4.170358,0.813791,0.647412,1.128953,donor6,B10678,donor6

In [33]:
def resolve_doublets(row, hto_columns, donor_id_to_max_donor, threshold=0.58):
    donor_id = row["donor_id"]
    current_donor = row["Donor"]
    fin_donor = row["fin_donor"]
    
    if fin_donor in ["Doublet", "Unassigned"] or current_donor != "Doublet":
        return row["fin_donor"]

    hto_values = row[hto_columns]
    sorted_hto = hto_values.sort_values(ascending=False)

    top1_name = sorted_hto.index[0].replace("HTO_", "")
    top1_val = sorted_hto.iloc[0]
    top2_val = sorted_hto.iloc[1]

    true_donor = donor_id_to_max_donor.get(donor_id)

    # Use ratio of second strongest to strongest HTO
    if (top2_val / top1_val) > threshold:
        return "Actual_Doublet"
    elif (top2_val / top1_val) < threshold:  # Optional: use absolute threshold for top1
         return true_donor
    else:
        return donor_id

In [34]:
filtered_df["f_donor"] = df.apply(
    resolve_doublets,
    axis=1,
    args=(hto_columns, donor_id_to_max_donor, 0.58)  # 0.2 is threshold, adjust if needed
)

In [35]:
filtered_df.to_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/both/step_2.csv", index=False)

In [36]:
filter_df = filtered_df[filtered_df["f_donor"].isin(df["donor_id"].unique())].copy()
filter_df.to_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/both/rest.csv", index=False)

In [37]:
filter_df

,barcode,Donor,donor_id,DoubletStatus,prob_max,prob_doublet,B30803,B10148,B40448,B20340,B30477,B10678,B30864,B30248,B30796,B10237,SNP_donor,best_hto,fin_donor,f_donor
28,AAACGGGGTCACCTAA-1,B40448,unassigned,Singlet,0.790,1.100000e-01,0.000000,0.282317,3.055751,0.644521,0.000000,0.364462,0.372974,0.000000,0.000000,0.232343,unassigned,B40448,unassigned,unassigned
29,AAACGGGGTCTGGTCG-1,B30803,donor6,Singlet,0.985,1.070000e-02,3.858473,0.282317,0.000000,0.000000,0.000000,0.198744,0.000000,0.944123,0.000000,1.128953,donor6,B30803,donor6,donor6
43,AAAGATGGTAAAGGAG-1,Negative,donor0,Negative,1.000,1.790000e-21,0.303170,0.502227,2.236318,0.644521,0.000000,0.364462,0.372974,0.000000,0.265076,0.232343,donor0,B40448,donor0,donor0
56,AAAGATGTCCTTGGTC-1,Negative,donor0,Negative,1.000,6.440000e-09,0.723887,0.502227,2.408616,0.000000,0.000000,0.000000,0.000000,0.487489,0.000000,0.000000,donor0,B40448,donor0,donor0
78,AAAGTAGCAATCCGAT-1,B10148,donor5,Singlet,0.917,7.790000e-02,0.303170,2.906273,1.163053,0.000000,0.155471,0.506582,0.857025,0.487489,0.265076,0.000000,donor5,B10148,donor5,donor5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8481,TTTACTGCACTGTCGG-1,B30864,unassigned,Singlet,0.866,9.000000e-02,0.000000,0.282317,0.198825,0.000000,0.289991,0.364462,3.639371,0.487489,0.265076,0.579226,unassigned,B30864,unassigned,unassigned
8485,TTTACTGGTTTGTTGG-1,B30248,unassigned,Singlet,0.702,1.900000e-01,0.000000,0.000000,0.000000,0.000000,0.155471,0.364462,0.000000,2.249291,0.647412,0.420750,unassigned,B30248,unassigned,unassigned
8517,TTTCCTCGTCTGATCA-1,B40448,unassigned,Singlet,0.492,3.400000e-01,0.303170,0.282317,3.334208,0.000000,0.514517,0.364462,0.644007,0.663891,0.000000,0.836278,unassigned,B40448,unassigned,unassigned
8558,TTTGGTTTCAACGAAA-1,Negative,donor1,Negative,0.976,1.150000e-02,0.303170,1.449735,0.364600,0.000000,0.289991,0.000000,0.203776,0.273161,0.000000,0.000000,donor1,B10148,donor1,donor1
8559,TTTGGTTTCACAAACC-1,B10148,donor2,Singlet,0.985,8.710000e-03,0.303170,4.827957,1.163053,0.000000,0.000000,0.630994,0.857025,0.000000,0.474406,0.232343,donor2,B10148,donor2,donor2

In [38]:

# Assuming filtered_df is your existing DataFrame
# Modify this condition as needed if you have specific criteria for "negative"
def update_f_donor(row):
    if row['Donor'] == 'Negative' and row['donor_id'] == 'unassigned':
        row['f_donor'] = 'Negative'
    return row

# Apply the function to update the 'f_donor' column based on the condition
filter_df = filter_df.apply(update_f_donor, axis=1)

# Check the result
print(filter_df[['Donor', 'donor_id', 'f_donor']])

         Donor    donor_id     f_donor
28      B40448  unassigned  unassigned
29      B30803      donor6      donor6
43    Negative      donor0      donor0
56    Negative      donor0      donor0
78      B10148      donor5      donor5
...        ...         ...         ...
8481    B30864  unassigned  unassigned
8485    B30248  unassigned  unassigned
8517    B40448  unassigned  unassigned
8558  Negative      donor1      donor1
8559    B10148      donor2      donor2

[279 rows x 3 columns]

In [56]:
filter_df.to_csv("/media/igl2/828f6e4d-cda7-48c0-99c1-478e80aeecda/Shubham/DS2/both/rest.csv", index=False)

In [50]:
def resolve_doublets(row, hto_columns, donor_id_to_max_donor, threshold=0.58):
    donor_id = row["donor_id"]
    current_donor = row["Donor"]
    fin_donor = row["fin_donor"]

    # Case: donor_id is unassigned and current Donor is Doublet
    if donor_id == "unassigned" and current_donor == "Doublet":
        hto_values = row[hto_columns]
        sorted_hto = hto_values.sort_values(ascending=False)

        top1_val = sorted_hto.iloc[0]
        top2_val = sorted_hto.iloc[1]

        ratio = top2_val / top1_val if top1_val != 0 else 0

        if ratio > threshold:
            return "Actual_Doublet"
        else:
            return "Negative"
    
    # If not matching the above condition, return the current fin_donor value
    return fin_donor

In [51]:
filter_df["fa_donor"] = filter_df.apply(
    resolve_doublets,
    axis=1,
    args=(hto_columns, donor_id_to_max_donor, 0.58)  # 0.2 is threshold, adjust if needed
)

In [52]:
filter_df

,barcode,Donor,donor_id,DoubletStatus,prob_max,prob_doublet,B30803,B10148,B40448,B20340,...,B10678,B30864,B30248,B30796,B10237,SNP_donor,best_hto,fin_donor,f_donor,fa_donor
28,AAACGGGGTCACCTAA-1,B40448,unassigned,Singlet,0.790,1.100000e-01,0.000000,0.282317,3.055751,0.644521,...,0.364462,0.372974,0.000000,0.000000,0.232343,unassigned,B40448,unassigned,unassigned,unassigned
29,AAACGGGGTCTGGTCG-1,B30803,donor6,Singlet,0.985,1.070000e-02,3.858473,0.282317,0.000000,0.000000,...,0.198744,0.000000,0.944123,0.000000,1.128953,donor6,B30803,donor6,donor6,donor6
43,AAAGATGGTAAAGGAG-1,Negative,donor0,Negative,1.000,1.790000e-21,0.303170,0.502227,2.236318,0.644521,...,0.364462,0.372974,0.000000,0.265076,0.232343,donor0,B40448,donor0,donor0,donor0
56,AAAGATGTCCTTGGTC-1,Negative,donor0,Negative,1.000,6.440000e-09,0.723887,0.502227,2.408616,0.000000,...,0.000000,0.000000,0.487489,0.000000,0.000000,donor0,B40448,donor0,donor0,donor0
78,AAAGTAGCAATCCGAT-1,B10148,donor5,Singlet,0.917,7.790000e-02,0.303170,2.906273,1.163053,0.000000,...,0.506582,0.857025,0.487489,0.265076,0.000000,donor5,B10148,donor5,donor5,donor5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8481,TTTACTGCACTGTCGG-1,B30864,unassigned,Singlet,0.866,9.000000e-02,0.000000,0.282317,0.198825,0.000000,...,0.364462,3.639371,0.487489,0.265076,0.579226,unassigned,B30864,unassigned,unassigned,unassigned
8485,TTTACTGGTTTGTTGG-1,B30248,unassigned,Singlet,0.702,1.900000e-01,0.000000,0.000000,0.000000,0.000000,...,0.364462,0.000000,2.249291,0.647412,0.420750,unassigned,B30248,unassigned,unassigned,unassigned
8517,TTTCCTCGTCTGATCA-1,B40448,unassigned,Singlet,0.492,3.400000e-01,0.303170,0.282317,3.334208,0.000000,...,0.364462,0.644007,0.663891,0.000000,0.836278,unassigned,B40448,unassigned,unassigned,unassigned
8558,TTTGGTTTCAACGAAA-1,Negative,donor1,Negative,0.976,1.150000e-02,0.303170,1.449735,0.364600,0.000000,...,0.000000,0.203776,0.273161,0.000000,0.000000,donor1,B10148,donor1,donor1,donor1
8559,TTTGGTTTCACAAACC-1,B10148,donor2,Singlet,0.985,8.710000e-03,0.303170,4.827957,1.163053,0.000000,...,0.630994,0.857025,0.000000,0.474406,0.232343,donor2,B10148,donor2,donor2,donor2

In [54]:
def resolve_doublets(row, hto_columns, donor_id_to_max_donor, threshold=0.58):
    donor_id = row["donor_id"]
    current_donor = row["Donor"]
    fin_donor = row["fa_donor"]

    # Case: donor_id is unassigned and current Donor is Doublet
    if donor_id == "Doublet" and current_donor == "Donor":
        hto_values = row[hto_columns]
        sorted_hto = hto_values.sort_va
        lues(ascending=False)

        top1_val = sorted_hto.iloc[0]
        top2_val = sorted_hto.iloc[1]

        ratio = top2_val / top1_val if top1_val != 0 else 0

        if ratio > threshold:
            return "Actual_Doublet"
        else:
            return "Negative"
    
    # If not matching the above condition, return the current fin_donor value
    return fin_donor

In [55]:
filter_df["fam_donor"] = filter_df.apply(
    resolve_doublets,
    axis=1,
    args=(hto_columns, donor_id_to_max_donor, 0.58)  # 0.2 is threshold, adjust if needed
)